"""Collect installed dependency license texts without downloading or executing packages."""

import importlib.metadata as metadata
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LICENSE_NAME = re.compile(r"^(?:licen[cs]e|copying|notice)(?:[._-].*)?$", re.I)


def section(name, version, license_id, sources):
    if not sources:
        raise SystemExit(f"Missing upstream license text for {name}")
    content = f"## {name} {version}\n\nDeclared license: {license_id or 'See upstream text below'}\n"
    for label, source in sources:
        # Preserve all terms; normalize line-ending whitespace for Git portability.
        text = "\n".join(line.rstrip() for line in source.read_text(encoding="utf-8", errors="strict").splitlines()).strip()
        content += f"\n### {label}\n\n```text\n{text}\n```\n"
    return content


def main():
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
    # Build tools are not imported into the application bundle.
    pending = sorted(set(package["dependencies"]) - {"vite", "@vitejs/plugin-react"})
    seen = set()
    frontend = []
    while pending:
        name = pending.pop(0)
        if name in seen:
            continue
        seen.add(name)
        folder = ROOT / "node_modules" / name
        row = json.loads((folder / "package.json").read_text(encoding="utf-8"))
        sources = [(p.name, p) for p in sorted(folder.iterdir()) if p.is_file() and LICENSE_NAME.match(p.name)]
        frontend.append((name, row["version"], row.get("license"), sources))
        pending.extend(sorted(row.get("dependencies", {})))
    backend = []
    constraints = (ROOT / "backend/requirements-dev.lock").read_text(encoding="utf-8")
    for name, expected in re.findall(r"^([A-Za-z0-9_.-]+)==([^\s]+)$", constraints, re.M):
        dist = metadata.distribution(name)
        if dist.version != expected:
            raise SystemExit(f"Installed {name} differs from the constraints file")
        sources = []
        for relative in sorted(dist.files or []):
            source = Path(dist.locate_file(relative))
            if source.is_file() and LICENSE_NAME.match(source.name):
                sources.append((str(relative).replace("\\", "/"), source))
        declared = dist.metadata.get("License-Expression") or dist.metadata.get("License")
        backend.append((name, expected, declared, sources))
    python_license = next((p for p in [Path(sys.base_prefix) / "LICENSE.txt", Path(sys.base_prefix) / "LICENSE"] if p.is_file()), None)
    if python_license is None:
        raise SystemExit("Python runtime license is missing; locate it before packaging")
    backend.append(("Python", ".".join(map(str, sys.version_info[:3])), "PSF-2.0 and included historical terms", [("LICENSE", python_license)]))
    folder = ROOT / "licenses"
    folder.mkdir(exist_ok=True)
    for filename, rows, scope in [
        ("frontend.md", frontend, "Application frontend imports and their declared transitive dependencies."),
        ("backend.md", backend, "Constrained Python dependencies (runtime, development and Windows packaging tools), plus the build environment's Python runtime. This includes tools that are not shipped in every application."),
    ]:
        output = f"# Third-party license texts\n\n{scope}\n\nGenerated by `scripts/generate-third-party-notices.py` from installed upstream files.\n\n"
        output += "\n".join(section(*row) for row in sorted(rows))
        (folder / filename).write_text(output, encoding="utf-8")
    notice = """# Third-party notices / 第三方组件说明

NPCs AI Studio's MIT license applies to project-authored material. It does not
replace upstream licenses. Preserve the applicable notices when redistributing.

本项目 MIT 许可证不替代第三方组件许可。分发时请携带对应版权和许可声明。

| Scope / 范围 | Complete upstream texts / 上游完整声明 |
| --- | --- |
| Frontend imports, including React, React Flow, icons, Inter and Noto Sans SC | [licenses/frontend.md](licenses/frontend.md) |
| Python runtime, constrained backend dependencies and packaging/development tools | [licenses/backend.md](licenses/backend.md) |

The bundled fonts retain SIL OFL 1.1, including their original copyright notices.
PyInstaller has a GPL exception for generated applications; it does not force
the project's code to adopt GPL. Other dependencies retain their own terms.
See the copied upstream texts for the authoritative terms and exceptions.

字体保留 OFL 许可与原版权说明。PyInstaller 生成程序适用其许可例外；它不会要求本项目
代码采用 GPL。具体条款以上游完整声明为准。

`npm ci` installs build-only Node dependencies under their own package licenses.
Those packages are not copied as `node_modules` into the application. If you
redistribute build tools or dependencies separately, retain their notices too.

Refresh these payloads after changing dependencies with
`python scripts/generate-third-party-notices.py` in the constrained build environment.
The distribution preparation copies these notices and license texts to
`dist/client/licenses/`; Windows packages also include a top-level copy.
Skill packages contain their own MIT `LICENSE` and generated project resources;
they do not include these external libraries or font binaries.
"""
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text(notice, encoding="utf-8")
    (ROOT / "backend/LICENSE").write_bytes((ROOT / "LICENSE").read_bytes())
    print(json.dumps({"frontend_components": len(frontend), "python_components": len(backend), "generated": True}))


if __name__ == "__main__":
    main()
