import {localizeLabels} from './i18n.js';
import { t, tm, useI18n } from './i18n';
import { useEffect, useRef, useState } from 'react';
import { Sparkle, WarningCircle, Check, Trash, ArrowCounterClockwise, FileText, MagnifyingGlass } from '@phosphor-icons/react';
import { Modal } from './Modal';
import { api } from './localApi';
import { useNavigationEditor } from './UnsavedNavigation';
import { draftScopeLabel } from './sceneGeneration';
import { reviewEntries, filterReviewEntries, reviewStates, deletionCommand, isEntryDeleted } from './draftReviewModel';
import './draftReview.css';

const labels=localizeLabels({name:'名称',role:'身份',goals:'长期目标',boundary:'行为底线',personality:'性格',voice:'口吻',story:'人物故事',description:'说明',uncertainties:'不确定信息',importance:'重要度',tags:'标签',nodes:'对话节点与选项',entry_node_id:'入口节点',entry_routes:'条件入口',character_id:'所属人物',body:'文本正文',text_type:'文本类型',author_id:'作者',condition:'出现条件'});
const states=localizeLabels({queued:'排队中',running:'生成中',awaiting_review:'待审核',applied:'已采用',completed:'已完成',draft:'草稿',failed:'失败',cancelled:'已取消',interrupted:'已中断'});
const fieldValues=view=>Object.fromEntries(view.fields.map(f=>[f.field,typeof f.candidate==='string'?f.candidate:JSON.stringify(f.candidate,null,2)]));
const display=value=>value==null?'未设置':typeof value==='string'?value:JSON.stringify(value,null,2);

export function DraftReviewWorkspace(props) {
  useI18n();
  const document=props.local.project._document;
  if(!document)return <div className="empty-state">{t("正在载入本地草稿…")}</div>;
  return <DraftInbox key={document.project_id} {...props}/>;
}

function DraftInbox({local,generation,announce,onGenerate,onRetry,onDirtyChange,onNavigationHandlers,onNavigate,initialRequest,onSceneContent,onOpenTarget,detailOnly=false,onClosed}) {
  useI18n();
  const document=local.project._document;
  const [scope,setScope]=useState(''),[filter,setFilter]=useState('pending'),[query,setQuery]=useState('');
  const [showProgress,setShowProgress]=useState(false);
  const [selected,setSelected]=useState(''),[failure,setFailure]=useState('');
  const [view,setView]=useState(null),[values,setValues]=useState({}),[chosen,setChosen]=useState({});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[edited,setEdited]=useState(false);
  const [closePrompt,setClosePrompt]=useState(null),[undo,setUndo]=useState(null),[bulkPrompt,setBulkPrompt]=useState(false);
  const loaded=useRef('');
  const entries=reviewEntries(document,generation.jobs);
  const visible=filterReviewEntries(entries,{scope,status:filter,query});
  const scoped=entries.filter(e=>!scope||e.task_id===scope);
  const pending=scoped.filter(e=>!e.deleted&&e.status==='pending');
  const failedEntry=entries.find(e=>e.key===failure);
  const selectedEntry=entries.find(e=>e.source==='draft'&&e.record_id===selected);
  const taskBusy=generation.jobs.some(j=>(!scope||j.id===scope)&&['queued','running'].includes(j.status));
  const writable=view?.status==='pending'&&!selectedEntry?.deleted;
  useEffect(()=>{setScope(initialRequest?.taskId || '');setSelected(initialRequest?.draftId || '');setFailure('');setFilter(reviewStates[initialRequest?.status]?initialRequest.status:'pending');setShowProgress(!!initialRequest?.showProgress);setQuery('');setView(null);setEdited(false);loaded.current='';},[initialRequest?.nonce,document.project_id]);
  useEffect(()=>{onDirtyChange?.(edited);return()=>onDirtyChange?.(false);},[edited,onDirtyChange]);
  useEffect(()=>{const handler=e=>{if(edited){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[edited]);
  useEffect(()=>{
    if(!selected){setView(null);return;}let active=true;
    if(loaded.current!==selected)setView(null);
    api(`/api/v2/projects/${document.project_id}/drafts/${selected}/review`).then(result=>{if(!active)return;setView(result);if(loaded.current!==selected){loaded.current=selected;setValues(fieldValues(result));setChosen(Object.fromEntries(result.fields.map(f=>[f.field,!f.protected])));setError('');}}).catch(reason=>{if(active)setError(reason.message);});
    return()=>{active=false;};
  },[document.project_id,document.revision,selected]);
  const close=()=>{setSelected('');setFailure('');setView(null);setEdited(false);setClosePrompt(null);setError('');loaded.current='';onClosed?.();};
  const requestClose=(after=()=>{})=>{if(busy)return;if(edited){setClosePrompt({after});return;}close();after();};
  const saveCandidate=async()=>{if(busy||!view)return false;setBusy(true);setError('');try{const patch=Object.fromEntries(view.fields.map(f=>[f.field,typeof f.candidate==='string'?values[f.field]:JSON.parse(values[f.field])]));await local.transact([{type:'put_draft',draft:{...view.draft,patch}}]);setEdited(false);announce(t("文本修改已保存，等待审核采用"));return true;}catch(reason){setError(reason instanceof SyntaxError?t("结构字段的 JSON 格式有误"):reason.message);return false;}finally{setBusy(false);}};
  useNavigationEditor(onNavigationHandlers,{dirty:edited,busy,name:view?.draft.name || '待审核文本',save:saveCandidate,discard:()=>{if(view)setValues(fieldValues(view));setEdited(false);return true;}});
  const command=async action=>{if(!view||busy)return;setBusy(true);setError('');try{const cmd={type:'review_draft',draft_id:selected,action,expected_author_hash:view.author_hash};if(action==='accept'){cmd.values=Object.fromEntries(view.fields.filter(f=>chosen[f.field]&&!f.protected).map(f=>[f.field,typeof f.candidate==='string'?values[f.field]:JSON.parse(values[f.field])]));if(!Object.keys(cmd.values).length)throw new Error(t("选择至少一个未确认字段"));}await local.transact([cmd]);close();announce(action==='accept'?t("已采用这份文本，可在对应场景或人物中查看"):t("已拒绝这份文本，可在已拒绝分类查看"));}catch(reason){setError(reason instanceof SyntaxError?t("数组或结构字段的 JSON 格式有误"):reason.message);}finally{setBusy(false);}};
  const rebase=async()=>{setBusy(true);setError('');try{await local.transact([{type:'rebase_draft',draft_id:selected,expected_author_hash:view.author_hash}]);announce(t("审核基准已更新，请核对后采用"));}catch(reason){setError(reason.message);}finally{setBusy(false);}};
  const setDeleted=async(entry,deleted)=>{if(busy)return;setBusy(true);setError('');try{await local.transact([deletionCommand(entry,deleted)]);if(deleted)setUndo(entry);else setUndo(null);close();announce(deleted?t("记录已移入已删除，可恢复；已采用的正式内容保留"):t("记录已恢复"));}catch(reason){setError(reason.message);}finally{setBusy(false);}};
  const bulk=async()=>{setBusy(true);setError('');try{const reviews=await Promise.all(pending.map(e=>api(`/api/v2/projects/${document.project_id}/drafts/${e.record_id}/review`)));if(reviews.some(r=>r.stale))throw new Error(t("部分文本的依据已变化，请打开卡片重新比较后再采用"));await local.transact(reviews.map(r=>({type:'review_draft',draft_id:r.draft.id,action:'accept',expected_author_hash:r.author_hash,values:Object.fromEntries(r.fields.filter(f=>!f.protected).map(f=>[f.field,f.candidate]))})));setBulkPrompt(false);announce(t("已采用 {0} 份文本", [reviews.length]));}catch(reason){setError(reason.message);}finally{setBusy(false);}};
  const openEntry=entry=>{setError('');loaded.current='';if(entry.source==='draft'){setFailure('');setSelected(entry.record_id);}else{setSelected('');setFailure(entry.key);}};
  const navigate=action=>requestClose(()=>onNavigate(action,'对应内容'));
  return <div className={detailOnly?"review-detail-only":`draft-workspace review-gallery ${!visible.length ? 'is-empty' : ''}`}>
    {!detailOnly&&<>
    <div className="workspace-heading"><div><small>{t("创作收件箱")}</small><h1>{t("草稿审核")}</h1><p>{t("每份文本独立审核，可分别采用。点击卡片查看全文与编辑。")}</p></div><button className="primary" onClick={onGenerate}><Sparkle size={15}/>{t("生成文本")}</button></div>
    <div className="review-status-tabs" role="tablist" aria-label={t("草稿状态")}>{Object.entries(reviewStates).map(([status,label])=><button role="tab" aria-selected={filter===status} className={filter===status?'active':''} key={status} onClick={()=>setFilter(status)}>{label}<span>{scoped.filter(e=>status==='deleted'?e.deleted:!e.deleted&&e.status===status).length}</span></button>)}</div>
    <div className="review-gallery-tools"><label className="review-search"><MagnifyingGlass size={16}/><input aria-label={t("搜索草稿")} placeholder={t("搜索名称或内容")} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label={t("审核生成批次")} value={scope} onChange={e=>setScope(e.target.value)}><option value="">{t("全部批次")}</option>{document.content.generation_history.slice().reverse().map((job,i)=><option key={job.id} value={job.id}>{t("批次 ")}{document.content.generation_history.length-i} · {job.name}</option>)}</select>{filter==='pending'&&<button className="secondary" disabled={busy||taskBusy||!pending.length} onClick={()=>setBulkPrompt(true)}>{t("批量采用 · ")}{pending.length}</button>}</div>
    {undo&&<div className="review-undo" role="status"><span>{t("已删除「")}{undo.name}」</span><button onClick={()=>setDeleted(undo,false)} disabled={busy}><ArrowCounterClockwise size={14}/>{t("撤销删除")}</button></div>}
    {(error&&!selected&&!failure&&!bulkPrompt)&&<p role="alert" className="danger">{tm(error)}</p>}{generation.error&&<p role="alert" className="danger">{tm(generation.error)}</p>}
    <div className="review-grid-caption"><strong>{t(reviewStates[filter])} · {visible.length}{t(" 份")}</strong><small>{filter==='failed'?t("失败项尚未产生文本，可重试或删除记录"):filter==='deleted'?t("恢复后回到原来的分类；正式工程内容保留"):t("点击卡片查看完整内容")}</small></div>
    <div className="review-card-grid">{visible.map(entry=><article key={entry.key} className={`review-card review-card-${entry.status}`}><button className="review-card-open" onClick={()=>openEntry(entry)} aria-label={t("查看{0} {1}", [entry.status==='failed'?t("失败记录"):t("草稿"), entry.name])}><div className="review-card-top"><FileText size={18}/><span className={`review-badge status-${entry.status}`}>{entry.deleted?t("已删除"):reviewStates[entry.status]}</span></div><h2>{entry.name}</h2><small className="review-card-scope">{draftScopeLabel(entry,document.content) || {character:'角色设定',dialogue:'角色对白',text:'非对话文本'}[entry.draft?.target.kind] || t("生成任务")}</small><p className="review-card-excerpt">{entry.preview}</p><small>{entry.model || t("历史草稿")}</small></button><footer><button className="subtle-button" onClick={()=>openEntry(entry)}>{entry.status==='failed'?t("查看失败原因"):t("打开全文")}</button>{entry.deleted?<button className="subtle-button" disabled={busy} onClick={()=>setDeleted(entry,false)}>{t("恢复")}</button>:<button className="review-delete" aria-label={t("删除记录 {0}", [entry.name])} title={t("删除记录，可恢复")} disabled={busy||['running','queued'].includes(entry.job?.status)} onClick={()=>setDeleted(entry,true)}><Trash size={15}/></button>}</footer></article>)}</div>
    {!visible.length&&<div className="review-empty workspace-empty"><FileText size={30}/><h2>{query?t("没有匹配的记录"):t("暂无{0}记录", [reviewStates[filter]])}</h2><p>{filter==='pending'?t("生成的文本会出现在这里，审核后再加入项目。"):t("可以切换分类或批次查看其他记录。")}</p></div>}
    <details className="review-task-history" open={showProgress} onToggle={e=>setShowProgress(e.currentTarget.open)}><summary>{t("生成批次与进度 · ")}{generation.jobs.length}{taskBusy?t(" · 有任务正在生成"):''}</summary><div>{generation.jobs.slice().reverse().map(job=><article key={job.id}><div><strong>{job.name}</strong><small>{states[job.status] || job.status} · {job.finished || 0}/{job.total || 0} · {job.profile_name || job.model || t("历史记录")}</small>{job.storage_error&&<p className="danger">{job.storage_error}</p>}</div><button className="secondary" onClick={()=>{setScope(job.id);setFilter(entries.some(e=>!e.deleted&&e.task_id===job.id&&e.status==='pending')?'pending':'failed');}}>{t("查看记录")}</button>{['queued','running'].includes(job.status)&&<button className="subtle-button" onClick={()=>generation.cancel(job)}>{t("取消任务")}</button>}</article>)}</div></details>
    </>}
    {selected&&<Modal title={selectedEntry?.name || t("草稿详情")} subtitle={t("核对文本后采用；高级字段与保护设置按需展开。")} wide className="review-detail-modal" onClose={()=>requestClose()}>
      {closePrompt&&<div className="review-close-prompt" role="alert"><strong>{t("文本修改尚未保存")}</strong><p>{t("保存这次编辑，还是直接关闭？")}</p><div><button className="secondary" disabled={busy} onClick={()=>{const after=closePrompt.after;close();after();}}>{t("不保存并关闭")}</button><button className="primary" disabled={busy} onClick={async()=>{const after=closePrompt.after;if(await saveCandidate()){close();after();}}}>{t("保存并关闭")}</button><button className="secondary" disabled={busy} onClick={()=>setClosePrompt(null)}>{t("取消")}</button></div></div>}
      <div className="review-detail-body" inert={closePrompt?true:undefined}>{error&&<p role="alert" className="danger">{tm(error)}</p>}{!view?<p className="empty-state">{error?t("无法读取详情，请关闭后重试"):t("正在读取草稿…")}</p>:<>
        <div className="review-detail-context"><span className={`review-badge status-${view.status}`}>{selectedEntry?.deleted?t("已删除"):reviewStates[view.status]}</span><small>{view.draft.model}{t(" · 依据内容 v")}{view.draft.base_content_revision}</small>{view.draft.scene_context&&<><strong>{draftScopeLabel(view.draft,document.content)}</strong><p>{view.draft.scene_context.group_name} · {view.draft.scene_context.mode==='pool'?t("采用后加入此场景的环境文本"):t("采用后关联到此人物在该场景的出场")}</p><button className="play-text-button" disabled={busy} onClick={()=>navigate(()=>onSceneContent(view.draft.scene_context))}>{t("查看对应场景")}</button></>}</div>
        {view.stale&&writable&&<div className="draft-stale"><WarningCircle size={18}/><div><strong>{t("生成依据已变化")}</strong><p>{t("展开字段差异核对当前内容，再更新审核基准。")}</p></div><button className="secondary" disabled={busy} onClick={rebase}>{t("重新比较")}</button></div>}
        <DraftPreview view={view} values={values} writable={writable} busy={busy} onChange={(field,value)=>{setValues(v=>({...v,[field]:value}));setEdited(true);}}/>
        <details className="review-advanced"><summary>{t("字段差异与条件 · 高级编辑")}</summary><div className="diff-header"><span>{t("采用字段")}</span><span>{t("当前正式内容")}</span><span>{t("待审核内容")}</span></div>{view.fields.map(f=><div key={f.field} className={`diff-row ${f.protected?'protected':''} ${f.conflict?'conflict':''}`}><label><input type="checkbox" aria-label={t("采用字段 {0}", [labels[f.field] || f.field])} checked={!!chosen[f.field]&&!f.protected} disabled={f.protected||!writable||busy} onChange={e=>setChosen(v=>({...v,[f.field]:e.target.checked}))}/><strong>{labels[f.field] || f.field}</strong>{f.protected&&<small>{t("已确认 · 保护")}</small>}{f.conflict&&<small>{t("人工修改冲突")}</small>}</label><div><pre>{display(f.current)}</pre>{f.conflict&&<details><summary>{t("生成时的内容")}</summary><pre>{display(f.base)}</pre></details>}</div><textarea aria-label={t("候选字段 {0}", [labels[f.field] || f.field])} value={values[f.field]??display(f.candidate)} disabled={f.protected||!writable||busy} rows={['story','nodes','body'].includes(f.field)?6:3} onChange={e=>{setValues(v=>({...v,[f.field]:e.target.value}));setEdited(true);}}/></div>)}</details>
        {!!view.issues.length&&<details className="review-advanced"><summary>{t("审核提醒 · ")}{view.issues.length}</summary>{view.issues.map((issue,i)=><p className="muted-text" key={i}>{issue}</p>)}</details>}
      </>}</div>
      {view&&<div className="review-detail-footer" inert={closePrompt?true:undefined}>{edited?<><span>{t("有未保存的修改")}</span><button className="secondary" disabled={busy} onClick={()=>{setValues(fieldValues(view));setEdited(false);}}>{t("放弃编辑")}</button><button className="secondary" disabled={busy} onClick={saveCandidate}>{t("保存修改")}</button></>:<button className="secondary" disabled={busy} onClick={()=>requestClose()}>{t("关闭")}</button>}{selectedEntry?.deleted?<button className="primary" disabled={busy} onClick={()=>setDeleted(selectedEntry,false)}>{t("恢复记录")}</button>:writable?<><button className="secondary" disabled={busy} onClick={()=>command('reject')}>{t("拒绝")}</button><button className="primary" disabled={busy||view.stale} onClick={()=>command('accept')}><Check size={15}/>{busy?t("处理中…"):t("采用这份文本")}</button></>:view.status==='accepted'?<button className="primary" disabled={busy} onClick={()=>navigate(()=>onOpenTarget(view.draft))}>{t("查看已采用内容")}</button>:null}</div>}
    </Modal>}
    {failedEntry&&<Modal title={t("生成失败记录")} subtitle={t("这项请求没有生成草稿内容，重试会新建任务。")} wide className="review-failure-modal" onClose={()=>requestClose()}><div className="review-detail-body"><span className="review-badge status-failed">{failedEntry.deleted?t("已删除"):t("生成失败")}</span><h3>{failedEntry.name}</h3><p>{draftScopeLabel(failedEntry,document.content)}</p><div className="review-failure-reason"><strong>{t("失败原因")}</strong><p>{failedEntry.preview}</p></div><small>{failedEntry.job.profile_name || failedEntry.model} · {failedEntry.model}</small>{error&&<p role="alert" className="danger">{tm(error)}</p>}</div><div className="review-detail-footer"><button className="secondary" disabled={busy} onClick={()=>requestClose()}>{t("关闭")}</button>{failedEntry.deleted?<button className="primary" disabled={busy} onClick={()=>setDeleted(failedEntry,false)}>{t("恢复记录")}</button>:<><button className="secondary" disabled={busy||['running','queued'].includes(failedEntry.job.status)} onClick={()=>setDeleted(failedEntry,true)}><Trash size={15}/>{t("删除记录")}</button>{failedEntry.item&&<button className="primary" disabled={busy||['running','queued'].includes(failedEntry.job.status)} onClick={()=>{close();onRetry({...failedEntry.job,items:[failedEntry.item]});}}><ArrowCounterClockwise size={15}/>{t("重试这一项")}</button>}</>}</div></Modal>}
    {bulkPrompt&&<Modal title={t("采用 {0} 份已保存文本？", [pending.length])} subtitle={t("当前批次范围内的待审核文本会分别加入对应场景或人物，并保留采用记录。")} onClose={()=>{if(!busy)setBulkPrompt(false);}}><div className="review-detail-body"><p>{t("批量采用不会合并这些文本。需要修改正文时，请先逐份打开卡片编辑并保存。")}</p>{error&&<p role="alert" className="danger">{tm(error)}</p>}</div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setBulkPrompt(false)}>{t("取消")}</button><button className="primary" disabled={busy||!pending.length} onClick={bulk}>{busy?t("处理中…"):t("采用 {0} 份", [pending.length])}</button></div></Modal>}
  </div>;
}

function DraftPreview({view,values,writable,busy,onChange}){
  useI18n();
  const stringFields=view.fields.filter(f=>typeof f.candidate==='string'&&['body','story','role','voice','personality','boundary','description'].includes(f.field)).sort((a,b)=>['body','story','role','voice','personality','boundary','description'].indexOf(a.field)-['body','story','role','voice','personality','boundary','description'].indexOf(b.field));
  let nodes=[];try{nodes=JSON.parse(values.nodes || '[]');}catch{/* Advanced editor displays malformed JSON for correction. */}
  return <div className="review-readable-content">{stringFields.map(f=><label key={f.field}>{t(labels[f.field])}{writable&&!f.protected?<textarea aria-label={t("草稿正文 {0}", [labels[f.field]])} rows={['body','story'].includes(f.field)?10:3} value={values[f.field] || ''} disabled={busy} onChange={e=>onChange(f.field,e.target.value)}/>:<p className="review-readable-text">{values[f.field]}</p>}</label>)}{Array.isArray(nodes)&&nodes.map((node,i)=><article className="review-dialogue-preview" key={node.id || i}><strong>{node.label || t("对白 {0}", [i+1])}</strong>{writable&&!view.fields.find(f=>f.field==='nodes')?.protected?<textarea aria-label={t("草稿台词 {0}", [i+1])} value={node.text} rows={3} disabled={busy} onChange={e=>onChange('nodes',JSON.stringify(nodes.map((n,j)=>j===i?{...n,text:e.target.value}:n),null,2))}/>:<p>{node.text}</p>}{node.options?.length>0&&<ol>{node.options.map((o,j)=><li key={o.id || j}>{o.text} <small>→ {o.target_node_id?nodes.find(n=>n.id===o.target_node_id)?.label || t("目标卡片"):t("结束对话")}</small></li>)}</ol>}</article>)}{!stringFields.length&&(!Array.isArray(nodes)||!nodes.length)&&<p className="muted-text">{t("展开高级编辑查看完整候选字段。")}</p>}</div>;
}
